<?php

/**
 * @file
 * Add Geo Redirect script from the frontend on all over the site.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_help().
 */
function alcon_geo_redirect_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.alcon_geo_redirect':
      $output = '<h2>' . t('About') . '</h2>';
      $output .= '<p>' . t('This module allows you to add geo redirect script in your site.') . '</p>';
      $output .= '<h2>' . t('Uses') . '</h2>';
      $output .= '<p>' . t('Geo redirect Scripts provides you the capability to quickly add Geo Redirect script in your site.') . '</p>';

      return $output;
  }
}

/**
 * Implements hook_page_attachments_alter().
 *
 * Alter CSS/JS files before they are output on the page.
 * which are defined on the settings page.
 */
function alcon_geo_redirect_page_attachments_alter(array &$attachments) {
  $header_section = \Drupal::config('alcon_geo_redirect.script.settings')->get();
  if (\Drupal::currentUser()->isAnonymous()) {
    if (isset($header_section['scripts_checkbox']) && isset($header_section['scripts']) && !empty($header_section['scripts'])) {
      $output_scripts = preg_split("/(<\/script>|<\/noscript>)/", $header_section['scripts']);
      $i = 1;
      $i = count($attachments['#attached']['html_head']) + 1;
      foreach ($output_scripts as $row) {

        if (empty($row)) {
          continue;
        }

        $script_tag  = 'script';
        $script_attr = [];
        $value       = '';

        $script_attributes = preg_replace('/(<script|<noscript)/', '', $row, 1);
        $get_script_attr   = preg_split('/(>)/', $script_attributes, 2);

        if (isset($get_script_attr[1])) {
          $value = $get_script_attr[1];
        }

        $get_script_tag = preg_split('/<noscript/', $row, 2);

        if (isset($get_script_tag[1])) {
          $script_tag = 'noscript';
        }

        if (isset($get_script_attr[0]) && !empty($get_script_attr[0])) {
          $get_attr   = preg_replace('/(\'|\")/', '', $get_script_attr[0]);
          $get_attr   = preg_replace('/\s+/', ',', $get_attr);
          $get_attr   = preg_replace('/(,=,|,=|=,)/', '=', $get_attr);
          $fetch_attr = explode(',', $get_attr);

          foreach ($fetch_attr as $attr) {
            if (empty($attr)) {
              continue;
            }

            $attr_key_value = explode('=', $attr);
            if (2 <= count($attr_key_value)) {
              $script_attr[$attr_key_value[0]] = preg_replace('/' . $attr_key_value[0] . '=/', '', $attr, 1);
            }
            else {
              $script_attr[$attr_key_value[0]] = $attr_key_value[0];
            }
          }
        }

        $attachments['#attached']['html_head'][$i] = [
          [
            '#type'  => 'html_tag',
            '#tag'   => $script_tag,
            '#value' => Markup::create($value),
          ],
          'header-and-footer-scripts-' . $i,
        ];
        if (!empty($script_attr)) {
          $attachments['#attached']['html_head'][$i][0]['#attributes'] = $script_attr;
        }
        $i++;
      }
    }
  }
}
