site_id: ''
rest_api_user: 'user.name'
rest_api_key: 'api_key_here'
rest_factories:
  dev: ''
  test: ''
  prod: ''
subdomain_pattern: '{subdomain}-{env}'
root_domain: ''
prod_web: ''
dev_web: ''
email_logs_from: ''
email_logs_to: ''
