entity.config_revision.canonical:
  route_name: entity.config_revision.canonical
  base_route: entity.config_revision.canonical
  title: 'View'
entity.config_revision.edit_form:
  route_name: entity.config_revision.edit_form
  base_route: entity.config_revision.canonical
  title: Edit
entity.config_revision.delete_form:
  route_name: entity.config_revision.delete_form
  base_route: entity.config_revision.canonical
  title: Delete
  weight: 10
