<?php

/**
 * @file
 * Contains apf_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function views_extras_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the apf_custom module.
    case 'help.page.apf_custom':
      $output = file_get_contents(\Drupal::service('extension.list.module')->getPath('views_extras') . '/README.md');
      return $output;

    default:
  }
}

/**
 * Implements hook_views_data().
 */
function views_extras_views_data() {
  $data['views']['extra_result'] = [
    'title' => t('Extra Result summary'),
    'help' => t('Shows result summary, for example the items per page.'),
    'area' => [
      'id' => 'extra_result',
    ],
  ];

  return $data;
}
