<?php

/**
 * @file
 * Provides site meta tag handlers.
 */

use Drupal\acsf\AcsfSite;

/**
 * Implements hook_page_attachments().
 */
function acsf_meta_page_attachments(array &$page) {
  $content = 'non-acsf';
  // Distinguish between ACSF infra and non-ACSF infra.
  if (!empty($GLOBALS['gardens_site_settings']['conf']['acsf_site_id'])) {
    $site = AcsfSite::load();
    $content = $site->site_name;
  }

  $description = [
    '#tag' => 'meta',
    '#attributes' => [
      'name' => 'acsf-site-name',
      'content' => $content,
    ],
  ];
  $page['#attached']['html_head'][] = [$description, 'acsf-site-name'];
}
