tealiumiq.settings:
  type: config_object
  label: 'Tealium iQ Settings'
  mapping:
    account:
      type: string
      label: 'Account'
    profile:
      type: string
      label: 'Profile'
    fpd_url:
      type: string
      label: 'First Party Domain URL'
    environment:
      type: string
      label: 'Environment'
    tag_load:
      type: string
      label: 'Utag Async or Sync'
    sync_load_position:
      type: string
      label: 'Add Tealium iQ Tags to the top or bottom of the page'
    api_only:
      type: boolean
      label: 'API Only'
    defaults_everywhere:
      type: boolean
      label: 'Defaults everywhere'
    defer_fields:
      type: boolean
      label: 'Defer fields'
    json_encoded:
      type: string
      label: 'JSON Encoded'
    utagsyncjs_load:
      type: boolean
      label: 'Load utag.sync.js'
    utaganonymous_only:
      type: boolean
      label: 'Track only anonymous'

tealiumiq.defaults:
  type: config_object
  label: 'Tealium iQ Defaults'
  mapping:
    page_name:
      type: string
      label: 'Page Name'
    page_url:
      type: string
      label: 'Page Url'
